all: diningphilosophers.ads diningphilosophers.adb diningphilosopherstest.adb
	gnatmake diningphilosophers.adb diningphilosopherstest.adb

clean:
	rm -f diningphilosophers diningphilosopherstest *.o *.ali
